#!/usr/bin/env python3
"""Convert ARC-AGI-2 JSON evaluation tasks to a Prolog fact file.

Usage: python3 tools/arc_agi2_to_prolog.py
Output: data/arc_agi_2/arc_tasks_2.pl

Each task becomes one arc2_task/4 fact:
    arc2_task(TaskId, TrainingPairs, TestInput, TestOutput).
TrainingPairs = list of pair(InputGrid, OutputGrid)
Grids = list of rows; each row = list of colour integers 0-9.

Source: ARC-AGI-2 public evaluation set, 120 tasks.
"""
import json, os

SRC = os.path.join(os.path.dirname(__file__), '..', 'data', 'arc_agi_2',
                   'arc_agi2_repo', 'data', 'evaluation')
OUT = os.path.join(os.path.dirname(__file__), '..', 'data', 'arc_agi_2', 'arc_tasks_2.pl')

def py_to_prolog(obj):
    """Convert a Python list (possibly nested) to a Prolog list atom."""
    if isinstance(obj, list):
        inner = ','.join(py_to_prolog(x) for x in obj)
        return f'[{inner}]'
    return str(obj)

files = sorted(f for f in os.listdir(SRC) if f.endswith('.json'))

lines = []
lines.append('% ARC-AGI-2 Public Evaluation Tasks -- auto-generated by tools/arc_agi2_to_prolog.py')
lines.append('% 120 tasks from the ARC-AGI-2 public evaluation set.')
lines.append('% Format: arc2_task(TaskId, TrainingPairs, TestInput, TestOutput).')
lines.append(':- module(arc_tasks_2, [arc2_task/4]).')
lines.append(':- discontiguous arc2_task/4.')
lines.append('')

for fn in files:
    task_id = fn.replace('.json', '')
    with open(os.path.join(SRC, fn)) as f:
        t = json.load(f)

    pairs = []
    for p in t['train']:
        inp = py_to_prolog(p['input'])
        out = py_to_prolog(p['output'])
        pairs.append(f'pair({inp},{out})')
    pairs_str = '[' + ',\n        '.join(pairs) + ']'

    test = t['test'][0]
    test_in  = py_to_prolog(test['input'])
    test_out = py_to_prolog(test['output'])

    lines.append(f"arc2_task('{task_id}',")
    lines.append(f"    {pairs_str},")
    lines.append(f"    {test_in},")
    lines.append(f"    {test_out}).")
    lines.append('')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines))

print(f'Written {len(files)} tasks to {OUT}')
