#!/usr/bin/env python3
"""Convert ARC-AGI-1 JSON training tasks to a Prolog fact file.

Usage: python3 tools/arc_agi_to_prolog.py
Output: data/arc_agi_1/arc_tasks.pl

Each task becomes one arc_agi_task/4 fact:
    arc_agi_task(TaskId, TrainingPairs, TestInput, TestOutput).
TrainingPairs = list of pair(InputGrid, OutputGrid)
Grids = list of rows; each row = list of colour integers 0-9.
"""
import json, os

SRC = os.path.join(os.path.dirname(__file__), '..', 'data', 'arc_agi_1')
OUT = os.path.join(SRC, 'arc_tasks.pl')

def py_to_prolog(obj):
    """Convert a Python list (possibly nested) to a Prolog list atom."""
    if isinstance(obj, list):
        inner = ','.join(py_to_prolog(x) for x in obj)
        return f'[{inner}]'
    return str(obj)

files = sorted(f for f in os.listdir(SRC) if f.endswith('.json'))

lines = []
lines.append('% ARC-AGI-1 Public Training Tasks — auto-generated by tools/arc_agi_to_prolog.py')
lines.append('% 400 tasks from the ARC-AGI public training set (Chollet 2019).')
lines.append('% Format: arc_agi_task(TaskId, TrainingPairs, TestInput, TestOutput).')
lines.append(':- module(arc_tasks, [arc_agi_task/4]).')
lines.append(':- discontiguous arc_agi_task/4.')
lines.append('')

for fn in files:
    task_id = fn.replace('.json', '')
    with open(os.path.join(SRC, fn)) as f:
        t = json.load(f)

    pairs = []
    for p in t['train']:
        inp = py_to_prolog(p['input'])
        out = py_to_prolog(p['output'])
        pairs.append(f'pair({inp},{out})')
    pairs_str = '[' + ',\n        '.join(pairs) + ']'

    test = t['test'][0]
    test_in  = py_to_prolog(test['input'])
    test_out = py_to_prolog(test['output'])

    lines.append(f"arc_agi_task('{task_id}',")
    lines.append(f"    {pairs_str},")
    lines.append(f"    {test_in},")
    lines.append(f"    {test_out}).")
    lines.append('')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines))

print(f'Written {len(files)} tasks to {OUT}')
